// Shared metadata pieces for public pages.
import type { Metadata } from "next";

export const SITE_URL = "https://oceanbluecorp.com";
export const SITE_NAME = "Oceanblue Solutions, Inc.";
export const ORG_ID = `${SITE_URL}/#organization`;
export const WEBSITE_ID = `${SITE_URL}/#website`;

/**
 * The card generated by src/app/opengraph-image.tsx.
 *
 * Next merges `openGraph` per key, not per field: a page that sets `openGraph`
 * replaces the parent's whole object, and the file-convention image only
 * attaches at the segment that owns the file. So every page that declares its
 * own openGraph must name the image again, or it shares with no picture.
 */
export const OG_IMAGES = [
  {
    url: "/opengraph-image",
    width: 1200,
    height: 630,
    alt: "Oceanblue Solutions, Inc. IT staffing, enterprise solutions, and managed services",
  },
];

/**
 * Metadata for a static public page: title, description, canonical, and a
 * matching Open Graph and Twitter card. `title` is the page part only; the root
 * template appends " | Oceanblue Solutions, Inc.". Keep it under ~35 characters
 * and the description between 120 and 160.
 */
export function pageMetadata({
  path,
  title,
  description,
  keywords,
  noIndex,
}: {
  path: string;
  title: string;
  description: string;
  keywords?: string[];
  noIndex?: boolean;
}): Metadata {
  const url = path === "/" ? SITE_URL : `${SITE_URL}${path}`;
  const full = `${title} | ${SITE_NAME}`;
  return {
    title,
    description,
    ...(keywords ? { keywords } : {}),
    alternates: { canonical: url },
    openGraph: {
      type: "website",
      siteName: SITE_NAME,
      locale: "en_US",
      url,
      title: full,
      description,
      images: OG_IMAGES,
    },
    twitter: { card: "summary_large_image", title: full, description },
    ...(noIndex ? { robots: { index: false, follow: true } } : {}),
  };
}

/**
 * Serialise a value for an inline <script> (JSON-LD, or a string literal).
 * `<` is escaped so authored text cannot close the tag, and U+2028/U+2029
 * because they are illegal in JS literals. Every inline script on a public
 * page goes through this, never a bare JSON.stringify.
 */
export function jsonLdString(data: unknown): string {
  return JSON.stringify(data)
    .replace(/</g, "\\u003c")
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
}

/** A BreadcrumbList from Home down to the current page. */
export function breadcrumbJsonLd(trail: { name: string; path: string }[]) {
  const items = [{ name: "Home", path: "/" }, ...trail];
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((c, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: c.name,
      item: c.path === "/" ? SITE_URL : `${SITE_URL}${c.path}`,
    })),
  };
}

/**
 * Breadcrumb trails for static public pages, below Home. Rendered as JSON-LD by
 * RouteBreadcrumbs. Pages that emit their own (solution detail, job, article)
 * are not listed.
 */
export const BREADCRUMB_TRAILS: Record<string, { name: string; path: string }[]> = {
  "/about": [{ name: "About", path: "/about" }],
  "/team": [{ name: "About", path: "/about" }, { name: "Leadership team", path: "/team" }],
  "/solutions": [{ name: "Solutions", path: "/solutions" }],
  "/solutions/engineering": [{ name: "Solutions", path: "/solutions" }, { name: "Engineering Talent & Services", path: "/solutions/engineering" }],
  "/products": [{ name: "Products", path: "/products" }],
  "/developers": [{ name: "Developers", path: "/developers" }],
  "/brand-kit": [{ name: "Media kit", path: "/brand-kit" }],
  "/careers": [{ name: "Careers", path: "/careers" }],
  "/careers/search": [{ name: "Careers", path: "/careers" }, { name: "Open jobs", path: "/careers/search" }],
  "/contact": [{ name: "Contact", path: "/contact" }],
  "/blog": [{ name: "Blog", path: "/blog" }],
  "/news": [{ name: "News", path: "/news" }],
  "/case-studies": [{ name: "Case Studies", path: "/case-studies" }],
  "/customer-stories": [{ name: "Customer Stories", path: "/customer-stories" }],
  "/status": [{ name: "System Status", path: "/status" }],
  "/faq": [{ name: "FAQ", path: "/faq" }],
  "/sitemap": [{ name: "Site map", path: "/sitemap" }],
  "/security": [{ name: "Security", path: "/security" }],
  "/legal": [{ name: "Legal", path: "/legal" }],
  "/privacy": [{ name: "Legal", path: "/legal" }, { name: "Privacy Policy", path: "/privacy" }],
  "/terms": [{ name: "Legal", path: "/legal" }, { name: "Terms of Service", path: "/terms" }],
  "/cookies": [{ name: "Legal", path: "/legal" }, { name: "Cookie Policy", path: "/cookies" }],
  "/accessibility": [{ name: "Legal", path: "/legal" }, { name: "Accessibility", path: "/accessibility" }],
  "/data-deletion": [{ name: "Legal", path: "/legal" }, { name: "Data deletion", path: "/data-deletion" }],
};
