// Shared metadata pieces for public pages.

/**
 * The card generated by src/app/opengraph-image.tsx.
 *
 * Next merges `openGraph` per key, not per field: a page that sets `openGraph`
 * replaces the parent's whole object, and the file-convention image only
 * attaches at the segment that owns the file. So every page that declares its
 * own openGraph must name the image again, or it shares with no picture.
 */
export const OG_IMAGES = [
  {
    url: "/opengraph-image",
    width: 1200,
    height: 630,
    alt: "Ocean Blue Corporation. IT staffing, enterprise solutions, and managed services",
  },
];
